version: '3.0'

services:
  
  frontend:
    container_name: 'frontend'
    build:
      context: ./client
      dockerfile: 'Dockerfile'
    ports: 
      - '8080:3000'
    depends_on:
      - backend
  backend:
    container_name: 'backend'
    build:
      context: ./server
      dockerfile: 'Dockerfile'
    environment:
      - BOOTSTRAP_IP=192.168.1.127
    volumes:
      - ./server/tmp:/usr/app/tmp
